spring:
  server:
    port: 8085
  data:
    mongodb:
      uri: mongodb://localhost:27017/projectdb

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
