spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/studentdb
jwt:
  secret: "your-secure-key-with-at-least-32-characters" # Debe coincidir con la del servicio de autenticación
  expiration: 86400000 # 1 día en milisegundos