spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notificationdb
  main:
    allow-bean-definition-overriding: true
  mail: # Debe estar al mismo nivel que "application" y "data"
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: "your-secure-key-with-at-least-32-characters" # Debe coincidir con la del servicio de autenticación
  expiration: 86400000 # 1 día en milisegundos
