# Configuración general del servicio
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/v1/projects/**

        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/api/v1/evaluations/**

        - id: researchline-service
          uri: lb://researchline-service
          predicates:
            - Path=/api/v1/researchlines/**

      # Configuración global de CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

# Configuración del servidor
server:
  port: 8080

# Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Configuración de JWT
jwt:
  secret: "your-secure-key-with-at-least-32-characters" # Debe coincidir con la del servicio de autenticación
  expiration: 86400000 # 1 día en milisegundos
