spring:
  application:
    name: student-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/studentdb
  main:
    allow-bean-definition-overriding: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: "your-secure-key-with-at-least-32-characters" # Debe coincidir con la del servicio de autenticación
  expiration: 86400000 # 1 día en milisegundos

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
