spring:
  application:
    name: authentication-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/authenticationdb
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: "your-secure-key-with-at-least-32-characters"
  expiration: 86400000 # 1 día en milisegundos

logging:
  level:
    org.springframework.security: DEBUG  # Log todos los eventos de seguridad para depuración
