# application.yml
spring:
  application:
    name: advisor-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/advisordb
  main:
    allow-bean-definition-overriding: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: "your-secure-key-with-at-least-32-characters" # Debe coincidir con la del servicio de autenticación
  expiration: 86400000 # 1 día en milisegundos