server:
  port: 8085
spring:
  application:
    name: project-service
  cloud:
    config:
      uri: http://localhost:8888
      discovery:
        enabled: true
      fail-fast: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: "your-secure-key-with-at-least-32-characters"
  expiration: 86400000 # 1 día en milisegundos
